resources:
  - url: /local/service-alarm.js
    type: module

title: Home
views:
  - path: default_view
    title: Home
    badges: []
    cards:
      - type: 'custom:service-alarm'
        duration_entity: input_number.lightalarm_duration
        mode_entity: input_select.lightalarm_options
        time_entity: input_datetime.lightalarm_time
      - type: entities
        title: Raw Entities
        show_header_toggle: false
        entities:
          - entity: input_datetime.lightalarm_time
          - entity: input_select.lightalarm_options
          - entity: input_number.lightalarm_duration
